# Generated by Django 3.2.15 on 2023-02-14 13:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('answer_value', models.CharField(max_length=100)),
                ('answer_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizCorrectAnswers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.quizanswers')),
            ],
        ),
        migrations.AddField(
            model_name='quizanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.quizquestions'),
        ),
    ]
