# Generated by Django 3.2.15 on 2023-02-14 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20230214_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='quiz_table',
            name='option3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz_table',
            name='option4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.state')),
            ],
        ),
    ]
