# Generated by Django 3.2.15 on 2023-02-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20230214_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswers',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
